# Solid Queue configuration
# This file configures how Solid Queue processes jobs

# Default configuration for all environments
default: &default
  # Number of threads for processing jobs
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1
  
  # Dispatcher configuration
  dispatchers:
    - polling_interval: 1
      batch_size: 500

# Development environment
development:
  <<: *default

# Test environment  
test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1

# Production environment
production:
  <<: *default
  workers:
    - queues: [critical, default, pipeline]
      threads: 10
      processes: 2
      polling_interval: 0.3
    - queues: [low]
      threads: 3
      processes: 1
      polling_interval: 1