# frozen_string_literal: true

class PublicController < ApplicationController
  # Public splash and overview pages. No auth required.
  def index
    # lightweight splash with a link to the deeper overview
  end

  def more
    # deep-dive overview of the app's vision and capabilities
    @features = [
      "Zero‑touch pipeline from intake to deliverables",
      "Rights-aware processing with provenance throughout",
      "Ten Pool Canon entity modeling (Idea, Manifest, Experience, …)",
      "Neo4j knowledge graph with vector search (GenAI)",
      "OpenAI-powered extraction using Structured Outputs",
      "Enliteracy scoring, gaps, and maturity assessment",
      "Autogenerated deliverables: exports, prompt packs, evaluation",
      "Knowledge Navigators (EKNs) for conversational exploration"
    ]
  end
end
